site_name: hid-usb-relay
site_url: https://auto-py-utils.github.io/hid-usb-relay/
site_description: "hid based usb relay package"
site_author:  auto-py-utils
repo_name: ""
repo_url: https://github.com/auto-py-utils/hid-usb-relay
edit_uri: blob/main/

nav:
  - Home: index.md
  - Source Manual: source-manual.md
  - USB Relay: usb_relay.md
  - API: api.md
  - CLI: cli.md
  - GUI: gui.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src  # Root level src if any
          options:
            docstring_style: google
            show_source: true
            merge_init_into_class: true
            show_docstring_modules: true
  - include-markdown:
      recursive: true
  - macros
  - search

theme:
  name: readthedocs
  features:
    - toc.integrate
    - search

extra_css:
  - _assets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@11.13.0/dist/mermaid.core.mjs
